### ISSUE TITLE
No date picker in Firefox and Safari

### ISSUE THREAD

**Issue by ericcirone** [brianblakely/nodep-date-input-polyfill#5] opened 2016-04-27 14:29 UTC
Hi, I cloned your project and built it. I ran the index.html file that is supplied and i do not get any date picker in Firefox or Safari. Am I missing something?

**Comment by jcgertig** [comment] 2016-05-20 03:23
try my fork

**Comment by brianblakely** [comment] 2016-05-30 18:12
Assuming this is a duplicate of #1, going by your comment in that thread.

**Closed by brianblakely** 2016-05-30 18:12 UTC
Labels: duplicate
